=== JJ/Algorithm-Evolutionary/xml/EvoSpec.dtd
<!-- EvoSpec language $Revision: 3.0 $ -->

<!ELEMENT ea ( initial, pop?) >
<!ATTLIST ea version NMTOKEN #REQUIRED >

<!ELEMENT initial ( pop?, op+ ) >

<!ELEMENT op ( param|code|op )+ >
<!ATTLIST op name NMTOKEN #REQUIRED >
<!ATTLIST op rate NMTOKEN #IMPLIED >
<!ATTLIST op type NMTOKEN #IMPLIED >

<!ELEMENT param ( param* ) >
<!ATTLIST param name NMTOKEN #REQUIRED >
<!ATTLIST param value NMTOKEN #IMPLIED >

<!ELEMENT src ( #PCDATA ) >

<!ELEMENT pop ( param*|section*|indi* ) >
<!ATTLIST pop size NMTOKEN #IMPLIED >

<!ELEMENT section ( param+ ) >
<!ATTLIST section name NMTOKEN #REQUIRED >

<!ELEMENT indi ( atom+ ) >
<!ATTLIST indi type NMTOKEN #REQUIRED >
<!ATTLIST indi fitness NMTOKEN #IMPLIED >

<!ELEMENT atom ( #PCDATA ) >

<!ELEMENT code ( src ) >
<!ATTLIST code language NMTOKEN #REQUIRED >
<!ATTLIST code type NMTOKEN #REQUIRED >

=== JJ/Algorithm-Evolutionary/xml/marea.xml
<?xml version="1.0"?>
<!DOCTYPE ea SYSTEM "EvoSpec.dtd">

<!-- Parameters for an evolutionary algorithm; also generation 0 of the same algorithm -->

<!--   
  This file is released under the GPL. See the LICENSE file included in this distribution,
  or go to http://www.fsf.org/licenses/gpl.txt

  CVS Info: $Date: 2009/07/24 08:46:59 $ 
  $Header: /media/Backup/Repos/opeal/opeal/Algorithm-Evolutionary/xml/marea.xml,v 3.0 2009/07/24 08:46:59 jmerelo Exp $ 
  $Author: jmerelo $ 
  $Revision: 3.0 $
  $Name $

-->

<ea version='0.4'>

  <initial>
    <op name='Creator' >
      <param name='number' value='20' />
      <param name='class' value='Vector' />       
      <param name='options'>
        <param name='length' value='2' />
	    <param name='rangestart' value='0' />
        <param name='rangeend' value='1' />
      </param>
    </op>

    <op name='Easy'  type='unary'>
       <param name='selrate' value='0.4' />
       <param name='maxgen' value='100' />
       <code type='eval' language='perl'>
    	  <src><![CDATA[ my $indi = shift;
	                 my ( $x, $y ) = @{$indi->{_array}};
		         my $sqrt = sqrt( $x*$x+$y*$y);
			 return sin( $sqrt )/$sqrt;
          ]]></src>
        </code>
        <op name='GaussianMutation' type='unary' rate='1'>
        	<param name='avg' value='0' />
		<param name='stddev' value='0.1' />
      	</op>
      	<op name='VectorCrossover' type='binary' rate='1'>
        	<param name='numPoints' value='1' />
      	</op>
      </op>
  </initial>

</ea>

=== JJ/Algorithm-Evolutionary/xml/onemax.xml
<?xml version="1.0"?>
<!DOCTYPE ea SYSTEM "EvoSpec.dtd">
<!-- Parameters for an evolutionary algorithm; also generation 0 of the same algorithm -->

<!--
  
  This file is released under the GPL. See the LICENSE file included in this distribution,
  or go to http://www.fsf.org/licenses/gpl.txt

  CVS Info: $Date: 2009/07/24 08:46:59 $ 
  $Header: /media/Backup/Repos/opeal/opeal/Algorithm-Evolutionary/xml/onemax.xml,v 3.0 2009/07/24 08:46:59 jmerelo Exp $ 
  $Author: jmerelo $ 
  $Revision: 3.0 $
  $Name $
-->

<ea version='0.4'>

  <initial>
    <op name='Creator' >
      <param name='number' value='20' />
      <param name='class' value='BitString' />       
      <param name='options'>
        <param name='length' value='64' />
      </param>
    </op>

    <op name='Easy' type='unary'>
        <param name='selrate' value='0.4' />
        <param name='maxgen' value='100' />
        <code type='eval' language='perl'>
    	  <src><![CDATA[ 
          my $indi = shift;
    	  my $total = 0;
    	  for ( my $i = 0; $i < length( $indi->{_str} ); $i ++ ) {
	  		$total += substr( $indi->{_str}, $i, 1 );
		  }
		  return $total;
    	  ]]>
          </src>
        </code>
        <op name='Bitflip' type='unary' rate='1.0'>
        	<param name='probability' value='0.1' />
            <param name='howMany' value='1' />
      	</op>
      	<op name='Crossover' type='binary' rate='1'>
        	<param name='numPoints' value='2' />
      	</op>
      </op>
  </initial>

</ea>

=== JJ/Algorithm-Evolutionary/xml/MMDP.xml
<?xml version="1.0"?>
<!DOCTYPE ea SYSTEM "EvoSpec.dtd">
<!-- Massively multimodal deceptive function. Ready for instantiating
     an 'Experiment' class
  CVS Info: $Date: 2008/02/13 13:08:22 $ 
  $Header: /media/Backup/Repos/opeal/opeal/Algorithm-Evolutionary/xml/MMDP.xml,v 1.1 2008/02/13 13:08:22 jmerelo Exp $ 
  $Author: jmerelo $ 
  $Revision: 1.1 $
  $Name $    

-->

  <ea version='0.4'>

  <initial>
    <pop size='1024'>
      <param name='type' value='BitString' /> 
      <param name='length' value='120' />
    </pop>

    <op name='Easy'  type='unary'>
        <param name='selrate' value='0.1' />
        <code type='eval' language='perl'>
    	  <src><![CDATA[  my $dude = shift;
  our @unitation = qw( 1 0 0.360384 0.640576 0.360384 0 1);
  our $block_size = 6;
  my $fitness = 0;
  my $str = $dude->{_str};
  for ( my $i = 0; $i < length($str); $i+= $block_size ) {
    my $block = substr( $str, $i, $block_size );
    my $ones = grep ( /1/, split(//,$block));
    $fitness += $unitation[$ones];
  }
  return $fitness;
          ]]></src>
        </code>
        <op name='Mutation' type='unary' rate='1'>
            <param name='mutRate' value='0.5' />
      	</op>
      	<op name='Crossover' type='binary' rate='2'>
        	<param name='numPoints' value='2' />
      	</op>
    </op>
    
    
  </initial>

</ea>

=== JJ/Algorithm-Evolutionary/xml/royalroad.xml
<?xml version="1.0"?>
<!DOCTYPE ea SYSTEM "EvoSpec.dtd">
<!-- Royal road function represented as an XML file. Ready for instantiating
     an 'Experiment' class
  CVS Info: $Date: 2009/02/04 20:43:15 $ 
  $Header: /media/Backup/Repos/opeal/opeal/Algorithm-Evolutionary/xml/royalroad.xml,v 2.1 2009/02/04 20:43:15 jmerelo Exp $ 
  $Author: jmerelo $ 
  $Revision: 2.1 $
  $Name $    

-->

  <ea version='0.4'>

  <initial>
    <pop size='256'>
      <param name='type' value='BitString' /> 
      <param name='length' value='64' />
    </pop>

    <op name='Easy'  type='unary'>
        <param name='selrate' value='0.4' />
        <param name='maxgen' value='100' />
        <code type='eval' language='perl'>
    	  <src><![CDATA[ my $chrom = shift;
                my $str = $chrom->Chrom();
                my $fitness = 0;
                my $blockSize = 4;
                for ( my $i = 0; $i < length( $str ) / $blockSize; $i++ ) {
	              my $block = 1;
	              for ( my $j = 0; $j < $blockSize; $j++ ) {
	                $block &= substr( $str, $i*$blockSize+$j, 1 );
	              }
	              ( $fitness += $blockSize ) if $block;
                }
                return $fitness;
          ]]></src>
        </code>
        <op name='Mutation' type='unary' rate='1'>
            <param name='mutRate' value='0.5' />
      	</op>
      	<op name='Crossover' type='binary' rate='0.5'>
        	<param name='numPoints' value='2' />
      	</op>
    </op>
    
    
  </initial>

</ea>
